
const MAD_LIB = getLongMadLib(); // You can try using both getShortMadLib() and getLongMadLib()

/**
 * This function is done for you.
 * This function is called when the page is initially loaded.
 * It will generate inputs based on the contents of the MAD_LIB.fillers list.
 * Each input has an associated label and error text that begins as empty.
 */
function setup() {
    let parentNode = document.getElementById("madlib-questions");

    for(let i = 0; i < MAD_LIB.fillers.length; i++) {
        let currLib = MAD_LIB.fillers[i];

        let newDivNode = document.createElement("div");
        newDivNode.className = "mb-2"

        let newInputNode = document.createElement("input");
        newInputNode.id = currLib.id + "-input";
        newInputNode.style.maxWidth = "25em";
        newInputNode.className = "form-control"
        newInputNode.placeholder = currLib.exampleText;
        
        let newLabelNode = document.createElement("label");
        newLabelNode.htmlFor = currLib.id + "-input";
        newLabelNode.innerText = currLib.friendlyText;

        let newErrorTextNode = document.createElement("p");
        newErrorTextNode.id = currLib.id + "-error-text";
        newErrorTextNode.style.color = "red";
        newErrorTextNode.innerText = "";

        newDivNode.appendChild(newLabelNode);
        newDivNode.append(newInputNode);
        newDivNode.append(newErrorTextNode);

        parentNode.appendChild(newDivNode);
    }
}

/**
 * This function is done for you.
 * This function is called anytime the user presses the "Generate!" button.
 * It first checks if the given inputs are valid. If they are valid,
 * the madlib is generated by calling the generateLib function.
 */
function generate() {
    if (validate()) {
        generateLib();
        alert("Success! Please see below for your MadLib :)");
    } else {
        alert("Uh oh, please check your form submission.")
    }
}

/**
 * This function is called by generate any time the user requests
 * generation and validation passes. Generate the `madlib-result` div
 * such that any existing HTML is replaced with the newest madlib contents.
 */
function generateLib() {
    const resultDiv = document.getElementById("madlib-result");
    resultDiv.innerHTML = "";

    let pBuilder = document.createElement("p"); 
    
    for (let i = 0; i < MAD_LIB.text.length; i++) {
        let currSegment = MAD_LIB.text[i];

        if (currSegment.segmentType === "static") {
            pBuilder.innerText += currSegment.text;
        } else if (currSegment.segmentType === "fillable") {
            let inputNode = document.getElementById(currSegment.id + "-input");
            pBuilder.innerText += inputNode.value;
        } else if (currSegment.segmentType === "newline") {
            resultDiv.appendChild(pBuilder);
            pBuilder = document.createElement("p");
        }
    }

    if (pBuilder.innerText !== "") {
        resultDiv.appendChild(pBuilder);
    }
}

/**
 * This function should check if any of the inputs have validation errors.
 * For each input, if it has validation errors, set the appropriate error text.
 * Otherwise, reset any error text that may exist. Use error text appropriate to
 * each form control, for exdample if validation fails on a quote, the error text
 * should say 'Please type 1 or more characters between quotes.' If the validation fails 
 * on a word, the error text should say 'Please type 1 or more letters, without spaces.'
 * 
 * Be sure to return true or false! Return true if all inputs are valid,
 * otherwise return false if ANY input is invalid.
 * 
 * @returns {boolean} true if form is valid, false otherwise.
 */
function validate() {
    let isValid = true;
    
    // TODO: If any inputs are invalid, set their error text.
    //       After checking ALL inputs, return true/false if
    //       the entire form was valid or not.
    for(let i = 0; i < MAD_LIB.fillers.length; i++) {
        let currLib = MAD_LIB.fillers[i];
        let currInputNode = document.getElementById(currLib.id + "-input");
        let currErrorTextNode = document.getElementById(currLib.id + "-error-text");

        let regex;
        let errorMessage;

        if (currLib.type === "word") {
            regex = /^[A-Za-z]+$/;
            errorMessage = "Please type 1 or more letters, without spaces or special characters.";
        } else if (currLib.type === "properNoun") {
            regex = /^[A-Z][A-Za-z]*$/;
            errorMessage = "Please type 1 or more letters, without special characters, starting with a capital letter.";
        } else if (currLib.type === "adjective") {
            regex = /^[A-Za-z]*[Yy]$/;
            errorMessage = "Please type 1 or more letters, without special characters, ending with a y.";
        } else if (currLib.type === "quote") {
            regex = /^(["'])([\s\S]+)\1$/;
            errorMessage = "Please type 1 or more characters between single or double quotes.";
        }

        if (!regex.test(currInputNode.value)) {
            currInputNode.classList.add("is-invalid");
            currErrorTextNode.innerText = errorMessage;
            isValid = false;
        } else {
            currInputNode.classList.remove("is-invalid");
            currErrorTextNode.innerText = "";
        }
    }

    return isValid;
}

// Don't remove this! It runs the setup function on page load.
window.onload = setup;
